### ISSUE TITLE
Does not work with Aeon ZW098-A52

### ISSUE THREAD

**Issue by kevinkey619** [vosmont/Vera-Plugin-RGBController#3]
This does NOT work with the Aeon ZW098-A52. The animations just turn the ZW098-A52 either solid yellow or solid green.

**Comment by vosmont** [comment]
It seems that the version 1.05 of the firmware of the Aeon bulb is buggy.
http://forum.micasaverde.com/index.php/topic,32613.msg293529.html#msg293529

**Comment by kevinkey619** [comment]
Yes, it turns out that there is definitely an issue with V1.5 of the ZW098-A52 firmware. Aeotec is still researching the issue and I should be getting a reply soon.
